version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP__ConnectionString: Uid=postgres;Pwd=123456;Server=db;Port=5432;Database=sheets;
    ports:
      - "8080:80"  
    expose:
      - "80"
    depends_on:
      - db

  db:    
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sheets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - app_data:/var/lib/postgresql/data

  test:
    image: test      
    build:
      context: .
      dockerfile: ./E2E/Dockerfile    
    environment:
      - API_URL=http://api:80
    depends_on:
      - api    

networks:
  default:
    name: dev-challenge

volumes:
  app_data: