// <auto-generated />
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(SheetsDbContext))]
    [Migration("20230926173502_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contracts.Database.Cell", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsExpression")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expression");

                    b.Property<string>("SheetId")
                        .HasColumnType("text")
                        .HasColumnName("sheet_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("SheetId");

                    b.ToTable("cells", "public");
                });

            modelBuilder.Entity("Contracts.Database.Sheet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("sheets", "public");
                });

            modelBuilder.Entity("Contracts.Database.Cell", b =>
                {
                    b.HasOne("Contracts.Database.Sheet", "Sheet")
                        .WithMany("Cells")
                        .HasForeignKey("SheetId");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("Contracts.Database.Sheet", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
