// <auto-generated />
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(SheetsDbContext))]
    [Migration("20230926212737_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contracts.Database.Cell", b =>
                {
                    b.Property<string>("SheetId")
                        .HasColumnType("text")
                        .HasColumnName("sheet_id");

                    b.Property<string>("CellId")
                        .HasColumnType("text")
                        .HasColumnName("cell_id");

                    b.Property<bool>("IsExpression")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expression");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("SheetId", "CellId");

                    b.ToTable("cells", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
